### ISSUE TITLE
Graph construction

### ISSUE THREAD

**Issue by Ung0d** [mslehre/MAS#3]
Write a class that:
* reads multiple fasta files
* splits the sequences into k-mers
* computes exact matches between k-mers of subsequent sequences
* eventually builds a graph datastructure with all k-mers with at least one match as nodes and where an edge represents a exact match of 2 k-mers

More precisely:
Let ![equation](https://latex.codecogs.com/png.latex?%5Cinline%20n_j) for ![equation](https://latex.codecogs.com/png.latex?%5Cinline%20j%20%5Cin%20%5C%7B1%2C...%2CS%5C%7D) denote the number of k-mers with at least one match in string j.

Consider the graph ![equation](https://latex.codecogs.com/png.latex?%5Cinline%20G%20%3D%20%28V%2CE%29) such that ![equation](https://latex.codecogs.com/png.latex?%5Cinline%20V%20%3D%20%5C%7B%28j%2Ci%29%20%7C%20j%20%5Cin%20%5C%7B1...S%5C%7D%20i%20%5Cin%20%5C%7B1...n_j%5C%7D%5C%7D) and ![equation](https://latex.codecogs.com/png.latex?%5Cinline%20E%20%3D%20%5C%7B%5C%2C%5C%2C%20%5C%7B%28j%2Ci%29%2C%20%28k%2Cl%29%5C%7D%20%5C%2C%5C%2C%20%7C%20%5C%2C%5C%2C%20%28j%2Ci%29%2C%28k%2Cl%29%20%5Cin%20V%20%5C%2C%5C%2C%20%5C%26%20%5C%2C%5C%2C%20S_j%5Ei%20%3D%20S_k%5El%20%5C%2C%5C%2C%20%5C%26%20%5C%2C%5C%2C%20k%20%3D%20j&plus;1%20%5C%2C%5C%2C%20%5C%7D).

**Comment by MarioStanke** [comment]
Isolated nodes (= _k_-mers which occur only in one of the sequences) are not created.
One need therefore only consider _k_-mers which occur in at least 2 sequences.

**Comment by sebastianbierb** [comment]
# class structure Graph
Graph(int k);
void readingFastaFiles(std::string nameData);
const std::vector<int>& getNumberOfKmer();
const std::vector<std::array<int,3>>& getEdgeList();
