### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by Ung0d** [mslehre/MAS#4]
Use the SFML-Library to write code that:
* opens a window
* renders a graph as described in #3 (make sure interfaces match)

You may want to start with an empty window, proceed with a single rectangle that optionally contains a string and then end up in plotting the whole k-mer graph.

This issue will define the main-function for the core program.

**Comment by Ung0d** [comment]
This may serve as a starting point: 
https://www.sfml-dev.org/tutorials/2.5/window-window.php

**Comment by MarioStanke** [comment]
How do you draw a line with SFML?

**Comment by Ung0d** [comment]
Draw shapes: https://www.sfml-dev.org/tutorials/2.5/graphics-shape.php
Lines with thickness: Rotated sf::RectangleShape
https://www.sfml-dev.org/documentation/2.5.1/classsf_1_1RectangleShape.php
Lines without thickness:  Use sf::Vertex
https://www.sfml-dev.org/documentation/2.5.1/classsf_1_1Vertex.php
