### ISSUE TITLE
Alignment state + actions

### ISSUE THREAD

**Issue by Ung0d** [mslehre/MAS#6]
Suppose the set E of edges in the graph defined in #3 is known (which corresponds to the set of possible k-mer alignment in subsequent sequences).

Let a state S denote the currently selected and **consistent subset of chosen edges**. Write a class to encapsulate such a state. Add a "possibleActions" method, that outputs a l**ist of valid moves given the current state**.

**Comment by mauricerad** [comment]
Die edges werden in einem Array der Länge 3 gespeichert. Der 1. Eintrag beschreibt den Index der 1. Sequenz (die zweite Sequenz ist dann Index der 1. +1), der 2. Eintrag ist der Index des k-mer in der 1. Sequenz und der 3. Eintrag der Index des k-mer in der 2. Sequenz.
