### ISSUE TITLE
compiler warnings "comparison between signed and unsigned integer expressions"

### ISSUE THREAD

**Issue by MarioStanke** [mslehre/MAS#60]
https://github.com/mslehre/MAS/blob/d8bb90d6ab84d067ade1e09387cde39bead13f3e/src/visualization/GraphRenderer.cpp#L175

Bitte die Warnungen von `make visualization` reparieren, z.B. mit cast.

**Comment by Luc4sQ** [comment]
Sobald ich an dem neuen Teilprojekt arbeite, werde ich das Problem sofort mit beheben!
