### ISSUE TITLE
coding style in State.cc

### ISSUE THREAD

**Issue by MarioStanke** [mslehre/MAS#62]
white space at line end:
https://github.com/mslehre/MAS/blob/f441ea57380182baaad8f7da6480518ebeb1c4c5/src/alignment/State.cc#L46
also: indentation in constructors

**Comment by MarioStanke** [comment]
Also please with spaces around operators like in the coding style:
```
edges[left].second.j>edges[i].second.j 
==> 
edges[left].second.j > edges[i].second.j
```

**Comment by mauricerad** [comment]
Timon is already working on this, I will clone his branch and try to help out.
