### ISSUE TITLE
bug in edge consistency

### ISSUE THREAD

**Issue by MarioStanke** [mslehre/MAS#63]
The boundary case is wrong: no two selected edges may share a node. In other words: each equivalence class of characters aligned with each other can contain at most one character from each sequence.

https://github.com/mslehre/MAS/blob/f441ea57380182baaad8f7da6480518ebeb1c4c5/src/alignment/State.cc#L33

This is a matter of changing `>` to `>=` or likewise.
Also: please make the consistency check for a pair of edges a separate function, e.g. 
`
bool consistent(Edge &e, Edge &f);
`

**Comment by mauricerad** [comment]
Timon has fixed the first issue, I will begin work on the second one now.

**Comment by TimonKapischke** [comment]
- The first issue is already fixed.
- The second issue is fixed in Feature/state_improvement
